# Generated by Django 2.0 on 2018-01-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180106_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='Aauthor',
        ),
    ]
