# Generated by Django 2.0 on 2018-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180106_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='media/Bugatti-Chiron.jpg', upload_to=''),
        ),
    ]
