# Generated by Django 2.0 on 2018-01-06 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180106_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Aauthor',
            new_name='author',
        ),
    ]
